name: Issue and Comment to Slack

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send message to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        if [ "${{ github.event_name }}" = "issues" ]; then
          response=$(curl -X POST -H 'Content-type: application/json' --data '{
            "channel": "#t-up-issue-tracker",
            "username": "ITK",
            "icon_emoji": ":ghost:",
            "text": "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nNew Issue: \n *Title:* ${{ github.event.issue.title }} \n *Description:* ${{ github.event.issue.body }} \n *ISSUE URL:* ${{ github.event.issue.html_url }}\n *TRACKER URL:* https://github.com/orgs/allket/projects/8"
          }' $SLACK_WEBHOOK_URL)
        
        elif [ "${{ github.event_name }}" = "issue_comment" ]; then  
          response=$(curl -X POST -H 'Content-type: application/json' --data '{
            "channel": "#t-up-issue-tracker",
            "username": "ITK",
            "icon_emoji": ":ghost:",
            "text": "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\nNew Comment: \n *Issue:* ${{ github.event.issue.title }} \n *Comment:* ${{ github.event.comment.body }} \n *COMMENT URL:* ${{ github.event.comment.html_url }}\n *TRACKER URL:* https://github.com/orgs/allket/projects/8"
          }' $SLACK_WEBHOOK_URL)
        fi

        # Check for invalid payload
        if [ "$response" != "ok" ]; then
          echo "Error: Slack Webhook returned $response. refer to https://api.slack.com/messaging/webhooks#handling_errors"
          exit 1
        fi

        echo "Slack message sent successfully."